### ISSUE TITLE
MyBatis主键自增Long类型反射异常

### ISSUE THREAD

**Issue by zjz6b6** [minbox-projects/api-boot#13]
SelectAutoKeyGenerator

`ResultMap.Builder builder = new ResultMap.Builder(statement.getConfiguration(), statement.getId() + "-Inline", **Integer.class**, new ArrayList(), true);`

虽然能够成功插入
但是日志报错

`org.apache.ibatis.reflection.ReflectionException: Could not set property 'id' of 'class ltd.beihu.black.orgmanager.model.ProdOption' with value '6' Cause: java.lang.IllegalArgumentException: argument type mismatch
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:185)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59)
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140)
	at com.gitee.hengboy.mybatis.enhance.key.generator.SelectAutoKeyGenerator.setValue(SelectAutoKeyGenerator.java:89)
	at com.gitee.hengboy.mybatis.enhance.key.generator.SelectAutoKeyGenerator.batchProcessAfter(SelectAutoKeyGenerator.java:76)
	at com.gitee.hengboy.mybatis.enhance.key.generator.SelectAutoKeyGenerator.processAfter(SelectAutoKeyGenerator.java:52)`

**Comment by hengboy** [comment]
@zjz6b6 数据库内具体是什么类型的？自增的字段建议在实体使用Integer来接收

**Comment by zjz6b6** [comment]
数据库是 bigint(20) 。
一般情况下用int就够，
但是特殊情况下，存日志，量大加上运行时间越长，容易溢出，以前公司就因为这个原因，导致服务不可用。

**Comment by hengboy** [comment]
嗯，`Integer`确实存在着这种问题，建议数据库使用`varchar`，对应实体类内使用String来定义字段类型，`@Id`注解支持`UUID`的主键策略 , `Mybatis Enhance`确实存在这个问题，`bigInt->Long`映射不可用，更新下个版本时会把这个问题一并解决，希望能提出一些宝贵的使用意见

**Comment by zjz6b6** [comment]
好的:+1:
