### ISSUE TITLE
I can't run the demo of ApiBootSecurityOauth

### ISSUE THREAD

**Issue by afterall3** [minbox-projects/api-boot#3]
Caused by: java.lang.NoClassDefFoundError: org/reflections/util/ConfigurationBuilder
	at org.minbox.framework.api.boot.common.tools.ClassTools.initReflections(ClassTools.java:47) ~[classes/:na]
	at org.minbox.framework.api.boot.common.tools.ClassTools.getSubClassList(ClassTools.java:61) ~[classes/:na]

**Comment by hengboy** [comment]
@afterall3 已经修复，将在2.0.4.RELEASE版本发布。
2.0.3.RELEASE及之前版本可以：
你先添加ApiBoot Http Converter组合使用，或者单独添加依赖：
```xml
<dependency>
        <groupId>org.reflections</groupId>
        <artifactId>reflections</artifactId>
</dependency>
```

**Comment by hengboy** [comment]
2.0.4.RELEASE已经发版，该问题已经修复
