### ISSUE TITLE
org.minbox.framework.logging.client.http.openfeign.LoggingOpenFeignInterceptor 异步执行 feign请求 抛异常

### ISSUE THREAD

**Issue by yulj1** [minbox-projects/api-boot#36]
错误信息：
ERROR 22536 --- [         task-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method:
异步执行feign请求时：

java.lang.NullPointerException: null
	at org.minbox.framework.logging.client.http.openfeign.LoggingOpenFeignInterceptor.apply(LoggingOpenFeignInterceptor.java:49)
	at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:169)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:99)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy206.getSmsTemplate(Unknown Source)

org.minbox.framework.logging.client.http.openfeign.LoggingOpenFeignInterceptor 
line： MinBoxLog log = LogThreadLocal.get();
因为异步执行，不在同个线程中，获取MinBoxLog log为空
是否jar包可以加个判 log是否为空处理

**Comment by hengboy** [comment]
@yulj1 好的，已经收到该问题，尽快处理

**Comment by hengboy** [comment]
@yulj1 请说下使用`ApiBoot`的版本

**Comment by yulj1** [comment]
@hengboy 2.1.7.RELEASE ,多谢 thanks a lot

**Comment by yulj1** [comment]
@hengboy       
hello,
主要依赖 minbox-logging 日志框架的    minbox-logging-client 1.0.5.RELEASE

org.minbox.framework.logging.client.http.openfeign.LoggingOpenFeignInterceptor 能否 和 LoggingRestTemplateInterceptor 一样  if (!ObjectUtils.isEmpty(log))增加 个判空处理.

 <dependency>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-client</artifactId>
            <version>1.0.5.RELEASE</version>
        </dependency>

**Comment by hengboy** [comment]
@yulj1 查看 [https://github.com/minbox-projects/minbox-logging/pull/2](https://github.com/minbox-projects/minbox-logging/pull/2)

**Comment by hengboy** [comment]
minbox-logging的1.0.6-SNAPSHOT版本新增了非空判断，使用方式如下所示：
```
<!--ApiBoot Logging-->
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>api-boot-starter-logging</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>minbox-logging-client</artifactId>
    <version>1.0.6-SNAPSHOT</version>
</dependency>
```

**Comment by yulj1** [comment]
@hengboy hello ，试了下 引入 
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>minbox-logging-client</artifactId>
    <version>1.0.6-SNAPSHOT</version>
</dependency>

程序运行会抛异常如下：
2020-07-31 19:47:21.622 ERROR 6780 --- [nio-8083-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause

java.lang.NoSuchMethodError: org.minbox.framework.web.util.HttpRequestUtil.isMultipart(Ljavax/servlet/ServletRequest;)Z
	at org.minbox.framework.logging.client.filter.LoggingBodyFilter.doFilter(LoggingBodyFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

依赖了配置：
  <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.minbox.framework</groupId>
                <artifactId>api-boot-dependencies</artifactId>
                <version>2.1.7.RELEASE</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        
        <dependency>
            <groupId>org.minbox.framework</groupId>
            <artifactId>api-boot-starter-logging</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-client</artifactId>
        </exclusion>
    </exclusions>
        </dependency>
        <dependency>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-client</artifactId>
            <version>1.0.6-SNAPSHOT</version>
        </dependency>
    </dependencies>

**Comment by hengboy** [comment]
使用2.3.0.RELEASE版本的ApiBoot

**Comment by yulj1** [comment]
OK 没问题了~  thank you ~

**Comment by hengboy** [comment]
@yulj1 非常感谢使用ApiBoot

**Comment by yulj1** [comment]
@hengboy  谢谢~ 可以 minbox-logging-client打个release 包 到Maven 中央仓库吗？因为服务器在 SG，下载tencent的maven依赖有些慢。麻烦

**Comment by hengboy** [comment]
现在这个快照版本的依赖是在Apache Maven Central内的

**Comment by yulj1** [comment]
@hengboy 麻烦了，查了下,最新版本是1.0.5.RELEASE
https://repo1.maven.org/maven2/org/minbox/framework/minbox-logging-client/

1.0.6-SNAPSHOT 国内从qcloud-central 下载到了依赖，
