### ISSUE TITLE
Mongo is not integrated, an exception occurs when the project starts

### ISSUE THREAD

**Issue by hengboy** [minbox-projects/api-boot#54]
```
Caused by: java.lang.ClassNotFoundException: org.minbox.framework.mongo.client.setting.SslSettings
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 25 common frames omitted
```

**Comment by hengboy** [comment]
The problem exists in the `2.3.0.RELEASE` version
